config/routes.rb
#               bloquear_usuario GET    /aprovacoes/bloquear-usuario/:id(.:format)  usuarios#bloquear_usuario
#                     aprovacoes GET    /aprovacoes(.:format)                       aprovacoes#aprovacoes
#                          sobre GET    /sobre(.:format)                            home#sobre
#                     admin_root GET    /admin(.:format)                            admin/dashboard#index
# batch_action_admin_publicacoes POST   /admin/publicacoes/batch_action(.:format)   admin/publicacoes#batch_action
#              admin_publicacoes GET    /admin/publicacoes(.:format)                admin/publicacoes#index
#                                POST   /admin/publicacoes(.:format)                admin/publicacoes#create
#           new_admin_publicacao GET    /admin/publicacoes/new(.:format)            admin/publicacoes#new
#          edit_admin_publicacao GET    /admin/publicacoes/:id/edit(.:format)       admin/publicacoes#edit
#               admin_publicacao GET    /admin/publicacoes/:id(.:format)            admin/publicacoes#show
#                                PATCH  /admin/publicacoes/:id(.:format)            admin/publicacoes#update
#                                PUT    /admin/publicacoes/:id(.:format)            admin/publicacoes#update
#                                DELETE /admin/publicacoes/:id(.:format)            admin/publicacoes#destroy
#    batch_action_admin_usuarios POST   /admin/usuarios/batch_action(.:format)      admin/usuarios#batch_action
#                 admin_usuarios GET    /admin/usuarios(.:format)                   admin/usuarios#index
#                                POST   /admin/usuarios(.:format)                   admin/usuarios#create
#              new_admin_usuario GET    /admin/usuarios/new(.:format)               admin/usuarios#new
#             edit_admin_usuario GET    /admin/usuarios/:id/edit(.:format)          admin/usuarios#edit
#                  admin_usuario GET    /admin/usuarios/:id(.:format)               admin/usuarios#show
#                                PATCH  /admin/usuarios/:id(.:format)               admin/usuarios#update
#                                PUT    /admin/usuarios/:id(.:format)               admin/usuarios#update
#                                DELETE /admin/usuarios/:id(.:format)               admin/usuarios#destroy
#     batch_action_admin_eventos POST   /admin/eventos/batch_action(.:format)       admin/eventos#batch_action
#                  admin_eventos GET    /admin/eventos(.:format)                    admin/eventos#index
#                                POST   /admin/eventos(.:format)                    admin/eventos#create
#               new_admin_evento GET    /admin/eventos/new(.:format)                admin/eventos#new
#              edit_admin_evento GET    /admin/eventos/:id/edit(.:format)           admin/eventos#edit
#                   admin_evento GET    /admin/eventos/:id(.:format)                admin/eventos#show
#                                PATCH  /admin/eventos/:id(.:format)                admin/eventos#update
#                                PUT    /admin/eventos/:id(.:format)                admin/eventos#update
#                                DELETE /admin/eventos/:id(.:format)                admin/eventos#destroy
#                admin_dashboard GET    /admin/dashboard(.:format)                  admin/dashboard#index
#  batch_action_admin_categorias POST   /admin/categorias/batch_action(.:format)    admin/categorias#batch_action
#               admin_categorias GET    /admin/categorias(.:format)                 admin/categorias#index
#                                POST   /admin/categorias(.:format)                 admin/categorias#create
#            new_admin_categoria GET    /admin/categorias/new(.:format)             admin/categorias#new
#           edit_admin_categoria GET    /admin/categorias/:id/edit(.:format)        admin/categorias#edit
#                admin_categoria GET    /admin/categorias/:id(.:format)             admin/categorias#show
#                                PATCH  /admin/categorias/:id(.:format)             admin/categorias#update
#                                PUT    /admin/categorias/:id(.:format)             admin/categorias#update
#                                DELETE /admin/categorias/:id(.:format)             admin/categorias#destroy
#                 admin_comments GET    /admin/comments(.:format)                   admin/comments#index
#                                POST   /admin/comments(.:format)                   admin/comments#create
#                  admin_comment GET    /admin/comments/:id(.:format)               admin/comments#show
#                                DELETE /admin/comments/:id(.:format)               admin/comments#destroy
#                           root GET    /                                           home#index
#
# Routes for Bootsy::Engine:
# image_gallery_images GET    /image_galleries/:image_gallery_id/images(.:format)     bootsy/images#index
#                      POST   /image_galleries/:image_gallery_id/images(.:format)     bootsy/images#create
#  image_gallery_image DELETE /image_galleries/:image_gallery_id/images/:id(.:format) bootsy/images#destroy
#               images GET    /images(.:format)                                       bootsy/images#index
#                      POST   /images(.:format)                                       bootsy/images#create
#                image DELETE /images/:id(.:format)                                   bootsy/images#destroy
#

Rails.application.routes.draw do
  
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  

  #resources :publicacaos
  resources :publicacoes

  #devise_for :admin_users, ActiveAdmin::Devise.config
  
  
  devise_for :usuarios, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'cadastro', edit: 'configuracoes' }
  get 'lista_usuarios' , to: 'usuarios#lista_usuarios', as: 'lista_usuarios'



  #PERFIL
  
  get '/perfil', to: 'perfis#show', as: 'perfil_usuario'
  get '/perfil_professor/:id', to: 'perfis#public_show', as: 'perfil_publico_usuario'
  # PERFIL - FOTO PERFIL
  get '/perfil/incluir_foto' , to: 'perfis#incluir_foto' , as: 'perfil_nova_foto'
  get '/perfil/alterar_foto' , to: 'perfis#alterar_foto' , as: 'perfil_alterar_foto'
  # PERFIL - FOTO CAPA
  get '/perfil/incluir_foto_capa' , to: 'perfis#incluir_foto_capa' , as: 'perfil_nova_foto_capa'
  get '/perfil/alterar_foto_capa' , to: 'perfis#alterar_foto_capa' , as: 'perfil_alterar_foto_capa'
  # PERFIL - DESCRICAO
  get '/perfil/incluir_descricao' , to: 'perfis#incluir_descricao' , as: 'perfil_nova_descricao' 
  get '/perfil/alterar_descricao' , to: 'perfis#alterar_descricao' , as: 'perfil_alterar_descricao'
  # PERFIL - DATAS
  get '/perfil/incluir_datas' , to: 'perfis#incluir_datas' , as: 'perfil_novas_datas' 
  get '/perfil/alterar_datas' , to: 'perfis#alterar_datas' , as: 'perfil_alterar_datas'
  # PERFIL - CORDA
  get '/perfil/incluir_corda' , to: 'perfis#incluir_corda' , as: 'perfil_nova_corda' 
  get '/perfil/alterar_corda' , to: 'perfis#alterar_corda' , as: 'perfil_alterar_corda' 

  #put '/editar_perfil/:id', to: 'perfis#update', as: 'update_perfil'
  resources :perfis, only: [:update, :create]

  #END PERFIL

  #--GEOGRAFIA----------------------------

  get '/geografia/:pais', to: 'geografia#estadosprovincias', as: 'geografia_estadosprovincias'
  get '/geografia/:pais/:estado', to: 'geografia#cidades', as: 'geografia_cidades'
  
  #get '/geografia/cidades/:pais:estado', to: 'geografia#cidade', as: 'geografia_cidades'


  #END GEOGRAFIA

  #--EVENTOS----------------------------
  
  resources :eventos

  get '/eventos-professores', to: 'eventos#index_professores', as: 'index_eventos_professores'
  get '/proximos-eventos', to: 'eventos#public_proximos_eventos', as: 'proximos-eventos'
  get '/proximos-eventos/evento/:id', to: 'eventos#public_evento', as: 'publico-evento'

  #filtro de eventos
  get '/proximos-eventos/local/:p',         to: 'eventos#public_proximos_eventos_local',           as: 'publico-evento-local'
  get '/proximos-eventos/local/',           to: 'eventos#public_proximos_eventos_sem_local',       as: 'publico-evento-sem-local'
  get '/proximos-eventos/data/:a/:m',       to: 'eventos#public_proximos_eventos_data',            as: 'publico-evento-data'
  get '/proximos-eventos/usuario/:idusuario',      to: 'eventos#public_proximos_eventos_usuario',   as: 'publico-evento-usuario'


  #get '/proximos-eventos/:id', to: 'eventos#public_evento'

  #END EVENTOS


  get '/publicacoes-professores', to: 'publicacoes#index_professores', as: 'index_publicacoes_professores'
  get '/todas-publicacoes', to: 'publicacoes#public_publicacoes', as: 'todas-publicacoes'
  get '/todas-publicacoes/:nomeCategoria', to: 'publicacoes#public_publicacoes', as: 'todas-publicacoes-categoria'
  get '/todas-publicacoes/publicacao/:id', to: 'publicacoes#public_publicacao', as: 'publico-publicacao'
  #get '/proximos-eventos/:id', to: 'eventos#public_evento'

  get '/aprovacoes/aprovar-usuario/:id', to: 'usuarios#aprovar_usuario', as: 'aprovar-usuario'
  get '/aprovacoes/bloquear-usuario/:id', to: 'usuarios#bloquear_usuario', as: 'bloquear-usuario'
  get '/aprovacoes', to: 'aprovacoes#aprovacoes', as: 'aprovacoes'

  get '/sobre', to: 'home#sobre', as: 'sobre'


  
  resources :turmas

  get '/turmas/nova-turma-sem-local/:id_local', to: 'turmas#new_turma_sem_local', as: 'new_turma_sem_local'

  resources :locais

  get '/encontre-a-capoeira', to: 'geolocalizacoes#index', as: 'geolocalizacoes'
  get '/encontre-a-capoeira/:tipo/:parametro', to: 'geolocalizacoes#index', as: 'geolocalizacoes-filtros'
  get '/encontre-a-capoeira/:id_local', to: 'geolocalizacoes#index_local', as: 'geolocalizacoes-local'
  get '/encontre-a-capoeira/:id_local/:id_turma', to: 'geolocalizacoes#index_local_turma', as: 'geolocalizacoes-local-turma'


  ActiveAdmin.routes(self)

app/controllers/locais_controller.rb
class LocaisController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]
  before_action :defineLocalizacaoNova, only: [:new, :create, :edit]


  # GET /locais
  # GET /locais.json
  def index
    @locais = Local.where(usuario: current_usuario).accessible_by(current_ability, :update).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /locais/1
  # GET /locais/1.json
  def show
  end

  # GET /locais/new
  def new
    @local = Local.new
  end

  # GET /locais/1/edit
  def edit
  end

  # POST /locais
  # POST /locais.json
  def create
    @local = Local.new(local_params)
    @local.usuario = current_usuario

    respond_to do |format|
      if @local.save
        format.html { redirect_to new_turma_sem_local_path @local, notice: 'Novo local cadastrado com sucesso. Verifique se já está aparecendo na lista' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locais/1
  # PATCH/PUT /locais/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to turmas_path, notice: 'Local atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locais/1
  # DELETE /locais/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Local excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  def defineLocalizacaoNova
      @paises_temp= CS.countries
      @paises_temp.delete("BR")
      @paises_temp[:BR] = "Brasil"
      @paises = @paises_temp.sort.map {|k,v| [v,k]}

      @estados =  Hash.new
      @cidades =  Hash.new
  end

  def defineLocalizacaoExistente(pais,estadoprovincia)
      @paises_temp = CS.countries
      @paises_temp.delete("BR")
      @paises_temp[:BR] = "Brasil"
      @paises = @paises_temp.sort.map {|k,v| [v,k]}
      @estados_temp =  CS.states(pais).sort.map {|k,v| [v,k]}
      @estados = @estados_temp
      @cidades =  CS.cities(estadoprovincia,pais)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_params
      params.require(:local).permit( :nome, :descricao, :endereco,
                                      :usuario, :imagem, :cidade, :pais, :estadoprovincia, :contato1, :contato2, :latitude, :longitude) # List here whitel
    end
end

app/helpers/locais_helper.rb
module LocaisHelper
end

app/views/locais/_form.html.erb
  <% if local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-10 col-sm-12 col-xs-12">
      <%= f.label :nome, "Nome:" %>
      <br>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-calendar-o" aria-hidden="true"></i>    
        </div>
        <%= f.text_field :nome, class: 'form-control', placeholder: 'Nome do Local' %>
      </div>
    </div>
  </div>


   <div class="row">
    <div class="col-md-10 col-sm-12 col-xs-12">
      <%= f.label :descricao , "Descrição:" %>
      <br>
      <div class="input-group">
       <div class="input-group-addon">
          <i class="fa fa-pencil" aria-hidden="true"></i>    
        </div>
        <%= f.text_area :descricao, class: 'form-control', placeholder: 'Descrição do local' %>
      </div>
    </div>
  </div>

  <div class="row">
  <div class="col-md-8 col-sm-12 col-xm-12">
      <%= f.label :endereco , "Endereço:"%>
      <br>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-map-marker" aria-hidden="true"></i>    
        </div>
        <%= f.text_field :endereco, class: 'form-control', placeholder: 'Rua / Número / Complemento / Bairro'%>
      </div>
    </div>
  </div>

  <div class="row">

     <div class="col-md-4 col-sm-12 col-xm-12">
      <%= f.label :pais , "País:"%>
      <br>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-globe" aria-hidden="true"></i>    
        </div>
        <%= f.select :pais, options_for_select(@paises,@local.pais),  prompt: "Escolha um país"%>
      </div>
    </div>

    <div class="col-md-4 col-sm-12 col-xm-12">
      <%= f.label :estadoprovincia , "Estado/Província:"%>
      <br>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-globe" aria-hidden="true"></i>    
        </div>
         <%= f.select   :estadoprovincia,
                        options_for_select(@estados,@local.estadoprovincia ),
                        prompt: "-------------",
                        class: 'form-control' 
                        %>
      </div>
    </div>

    <div class="col-md-4 col-sm-12 col-xm-12">
      <%= f.label :cidade , "Cidade:"%>
      <br>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-globe" aria-hidden="true"></i>    
        </div>
        <%= f.select      :cidade,
                          options_for_select(@cidades,@local.cidade),
                          prompt: "-------------",
                          class: 'form-control'
                          %>
      </div>
    </div>

    

  </div>

  <div class="row">
    <div class="col-md-4 col-sm-12 col-xs-12">
     <%= f.label :contato1, "Telefone de Contato:" %>
      <br>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-phone" aria-hidden="true"></i>    
        </div>
        <%= f.text_field :contato1, class: 'form-control', placeholder: 'Telefone de Contato' %>
      </div>
    </div>
    <div class="col-md-4 col-sm-12 col-xs-12">
     <%= f.label :contato2, "E-mail de Contato:" %>
      <br>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-envelope-o" aria-hidden="true"></i>    
        </div>
        <%= f.text_field :contato2, class: 'form-control', placeholder: 'E-mail de Contato' %>
      </div>
    </div>
  </div>

   <div class="row">
    
    <div class="col-md-5 col-sm-12 col-xm-12">
      
      <div class="input-group">
        <% if @local.imagem? %> 
        <%= f.label :imagem , "Alterar Imagem:"%>
        <%else%>
        <%= f.label :imagem , "Imagem:"%>
        <% end %>
        <br>
       <%= f.file_field :imagem, id:'foto-local' %>
       
       
      </div>
    </div>
    <div class="col-md-4">
      <% if @local.imagem? %> 
        <%= f.label :imagem , "Imagem Atual:"%>
        <br>
        <%= image_tag(@local.imagem_url, height:'50') %> 
      <% end %>  
    </div>
  </div>

app/views/locais/edit.html.erb
<h1>Editar Local</h1>


<%= form_for(@local) do |f| %>

			<%= render 'form', local: @local, f:f %>


			<% #opcao disponivel somente ao editar %>

			<div class="actions">
				<%= f.submit "Salvar alterações do Local",:class => "btn btn-success btn-mini"%>
			</div>

			<% end %>

<%= link_to 'Visualizar', @local %> |
<%= link_to 'Excluir', @local, method: :delete, data: { confirm: 'Tem certeza que deseja excluir este local?' } %> |
<%= link_to 'Voltar', turmas_path %>
<br>

app/views/locais/index.html.erb
<h1>Meus Cadastrados de Locais</h1>

<div class="alert alert-info" role="alert">
    Estes são os locais cadastrados por você. Estes locais estão disponiveis para serem selecionados na tela de cadastro de turmas..
  </div>

<p id="notice"><%= notice %></p>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Local</th>
      <th></th>
      <th class="text-center">Contatos</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locais.each do |local| %>
      <tr>
        <td><%=image_tag local.imagem_url.to_s, size: '70'%></td>
        <td>
           <%=local.nome%><br>
           <%=local.endereco%><br>
           <%=local.cidade%><br>
           <%=local.estadoprovincia%> - <%=local.pais%>
        </td>
        <td class="text-center">
           <%=local.contato1%><br>
           <%=local.contato2%><br>
        </td>
        <td>
          
          <%= link_to(local) do %>
            <i class="fa fa-calendar-o"></i> Visualizar
          <% end %>
          <br>
          <%= link_to(edit_local_path(local)) do %>
            <i class="fa fa-pencil"></i> Editar
          <% end %>
          <br>
          <%= link_to(local, method: :delete, data: { confirm: 'Tem certeza que deseja excluir este local?' }) do %>
            <i class="fa fa-trash-o"></i> Excluir
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @locais %>

<br>


<%= link_to turmas_path do %>
  <i class="fa fa-users"></i> Voltar para tela de Turmas
<% end %>

app/views/locais/new.html.erb
		<h1>Cadastrar Novo Local</h1>

		<%= form_for(@local) do |f| %>

			<%= render 'form', local: @local, f:f %>
			
			<div class="actions">
   				<%= f.submit "Cadastrar Local" , :class => "btn btn-success"%>
  			
			</div>

		<% end %> 


		<%= link_to 'Voltar', locais_path %>
		<br>

app/views/locais/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Local</h2>


<p><%=@local.nome%></p>
<p><%=@local.endereco_completo%></p>
<p><%=@local.contato1%></p>
<p><%=@local.contato2%></p>

<p>


<%=image_tag(	"https://maps.googleapis.com/maps/api/staticmap
				?center=#{@local.latitude},#{@local.longitude}
				&zoom=16
				&size=300x300
				&maptype=roadmap
				&markers=color:blue%7Clabel:#{@local.nome}%7C#{@local.latitude},#{@local.longitude}
				&key=AIzaSyBRm2ob56GOjnSIKFxPYrp04haa0c4Gdsc"
)%>





</p>


<%= link_to 'Editar Local', edit_local_path(@local) %> |
<%= link_to 'Voltar para lista de locais', locais_path %>