config/routes.rb
#               bloquear_usuario GET    /aprovacoes/bloquear-usuario/:id(.:format)  usuarios#bloquear_usuario
#                     aprovacoes GET    /aprovacoes(.:format)                       aprovacoes#aprovacoes
#                          sobre GET    /sobre(.:format)                            home#sobre
#                     admin_root GET    /admin(.:format)                            admin/dashboard#index
# batch_action_admin_publicacoes POST   /admin/publicacoes/batch_action(.:format)   admin/publicacoes#batch_action
#              admin_publicacoes GET    /admin/publicacoes(.:format)                admin/publicacoes#index
#                                POST   /admin/publicacoes(.:format)                admin/publicacoes#create
#           new_admin_publicacao GET    /admin/publicacoes/new(.:format)            admin/publicacoes#new
#          edit_admin_publicacao GET    /admin/publicacoes/:id/edit(.:format)       admin/publicacoes#edit
#               admin_publicacao GET    /admin/publicacoes/:id(.:format)            admin/publicacoes#show
#                                PATCH  /admin/publicacoes/:id(.:format)            admin/publicacoes#update
#                                PUT    /admin/publicacoes/:id(.:format)            admin/publicacoes#update
#                                DELETE /admin/publicacoes/:id(.:format)            admin/publicacoes#destroy
#    batch_action_admin_usuarios POST   /admin/usuarios/batch_action(.:format)      admin/usuarios#batch_action
#                 admin_usuarios GET    /admin/usuarios(.:format)                   admin/usuarios#index
#                                POST   /admin/usuarios(.:format)                   admin/usuarios#create
#              new_admin_usuario GET    /admin/usuarios/new(.:format)               admin/usuarios#new
#             edit_admin_usuario GET    /admin/usuarios/:id/edit(.:format)          admin/usuarios#edit
#                  admin_usuario GET    /admin/usuarios/:id(.:format)               admin/usuarios#show
#                                PATCH  /admin/usuarios/:id(.:format)               admin/usuarios#update
#                                PUT    /admin/usuarios/:id(.:format)               admin/usuarios#update
#                                DELETE /admin/usuarios/:id(.:format)               admin/usuarios#destroy
#     batch_action_admin_eventos POST   /admin/eventos/batch_action(.:format)       admin/eventos#batch_action
#                  admin_eventos GET    /admin/eventos(.:format)                    admin/eventos#index
#                                POST   /admin/eventos(.:format)                    admin/eventos#create
#               new_admin_evento GET    /admin/eventos/new(.:format)                admin/eventos#new
#              edit_admin_evento GET    /admin/eventos/:id/edit(.:format)           admin/eventos#edit
#                   admin_evento GET    /admin/eventos/:id(.:format)                admin/eventos#show
#                                PATCH  /admin/eventos/:id(.:format)                admin/eventos#update
#                                PUT    /admin/eventos/:id(.:format)                admin/eventos#update
#                                DELETE /admin/eventos/:id(.:format)                admin/eventos#destroy
#                admin_dashboard GET    /admin/dashboard(.:format)                  admin/dashboard#index
#  batch_action_admin_categorias POST   /admin/categorias/batch_action(.:format)    admin/categorias#batch_action
#               admin_categorias GET    /admin/categorias(.:format)                 admin/categorias#index
#                                POST   /admin/categorias(.:format)                 admin/categorias#create
#            new_admin_categoria GET    /admin/categorias/new(.:format)             admin/categorias#new
#           edit_admin_categoria GET    /admin/categorias/:id/edit(.:format)        admin/categorias#edit
#                admin_categoria GET    /admin/categorias/:id(.:format)             admin/categorias#show
#                                PATCH  /admin/categorias/:id(.:format)             admin/categorias#update
#                                PUT    /admin/categorias/:id(.:format)             admin/categorias#update
#                                DELETE /admin/categorias/:id(.:format)             admin/categorias#destroy
#                 admin_comments GET    /admin/comments(.:format)                   admin/comments#index
#                                POST   /admin/comments(.:format)                   admin/comments#create
#                  admin_comment GET    /admin/comments/:id(.:format)               admin/comments#show
#                                DELETE /admin/comments/:id(.:format)               admin/comments#destroy
#                           root GET    /                                           home#index
#
# Routes for Bootsy::Engine:
# image_gallery_images GET    /image_galleries/:image_gallery_id/images(.:format)     bootsy/images#index
#                      POST   /image_galleries/:image_gallery_id/images(.:format)     bootsy/images#create
#  image_gallery_image DELETE /image_galleries/:image_gallery_id/images/:id(.:format) bootsy/images#destroy
#               images GET    /images(.:format)                                       bootsy/images#index
#                      POST   /images(.:format)                                       bootsy/images#create
#                image DELETE /images/:id(.:format)                                   bootsy/images#destroy
#

Rails.application.routes.draw do
  
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  

  #resources :publicacaos
  resources :publicacoes

  #devise_for :admin_users, ActiveAdmin::Devise.config
  
  
  devise_for :usuarios, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'cadastro', edit: 'configuracoes' }
  get 'lista_usuarios' , to: 'usuarios#lista_usuarios', as: 'lista_usuarios'



  #PERFIL
  
  get '/perfil', to: 'perfis#show', as: 'perfil_usuario'
  get '/perfil_professor/:id', to: 'perfis#public_show', as: 'perfil_publico_usuario'
  # PERFIL - FOTO PERFIL
  get '/perfil/incluir_foto' , to: 'perfis#incluir_foto' , as: 'perfil_nova_foto'
  get '/perfil/alterar_foto' , to: 'perfis#alterar_foto' , as: 'perfil_alterar_foto'
  # PERFIL - FOTO CAPA
  get '/perfil/incluir_foto_capa' , to: 'perfis#incluir_foto_capa' , as: 'perfil_nova_foto_capa'
  get '/perfil/alterar_foto_capa' , to: 'perfis#alterar_foto_capa' , as: 'perfil_alterar_foto_capa'
  # PERFIL - DESCRICAO
  get '/perfil/incluir_descricao' , to: 'perfis#incluir_descricao' , as: 'perfil_nova_descricao' 
  get '/perfil/alterar_descricao' , to: 'perfis#alterar_descricao' , as: 'perfil_alterar_descricao'
  # PERFIL - DATAS
  get '/perfil/incluir_datas' , to: 'perfis#incluir_datas' , as: 'perfil_novas_datas' 
  get '/perfil/alterar_datas' , to: 'perfis#alterar_datas' , as: 'perfil_alterar_datas'
  # PERFIL - CORDA
  get '/perfil/incluir_corda' , to: 'perfis#incluir_corda' , as: 'perfil_nova_corda' 
  get '/perfil/alterar_corda' , to: 'perfis#alterar_corda' , as: 'perfil_alterar_corda' 

  #put '/editar_perfil/:id', to: 'perfis#update', as: 'update_perfil'
  resources :perfis, only: [:update, :create]

  #END PERFIL

  #--GEOGRAFIA----------------------------

  get '/geografia/:pais', to: 'geografia#estadosprovincias', as: 'geografia_estadosprovincias'
  get '/geografia/:pais/:estado', to: 'geografia#cidades', as: 'geografia_cidades'
  
  #get '/geografia/cidades/:pais:estado', to: 'geografia#cidade', as: 'geografia_cidades'


  #END GEOGRAFIA

  #--EVENTOS----------------------------
  
  resources :eventos

  get '/eventos-professores', to: 'eventos#index_professores', as: 'index_eventos_professores'
  get '/proximos-eventos', to: 'eventos#public_proximos_eventos', as: 'proximos-eventos'
  get '/proximos-eventos/evento/:id', to: 'eventos#public_evento', as: 'publico-evento'

  #filtro de eventos
  get '/proximos-eventos/local/:p',         to: 'eventos#public_proximos_eventos_local',           as: 'publico-evento-local'
  get '/proximos-eventos/local/',           to: 'eventos#public_proximos_eventos_sem_local',       as: 'publico-evento-sem-local'
  get '/proximos-eventos/data/:a/:m',       to: 'eventos#public_proximos_eventos_data',            as: 'publico-evento-data'
  get '/proximos-eventos/usuario/:idusuario',      to: 'eventos#public_proximos_eventos_usuario',   as: 'publico-evento-usuario'


  #get '/proximos-eventos/:id', to: 'eventos#public_evento'

  #END EVENTOS


  get '/publicacoes-professores', to: 'publicacoes#index_professores', as: 'index_publicacoes_professores'
  get '/todas-publicacoes', to: 'publicacoes#public_publicacoes', as: 'todas-publicacoes'
  get '/todas-publicacoes/:nomeCategoria', to: 'publicacoes#public_publicacoes', as: 'todas-publicacoes-categoria'
  get '/todas-publicacoes/publicacao/:id', to: 'publicacoes#public_publicacao', as: 'publico-publicacao'
  #get '/proximos-eventos/:id', to: 'eventos#public_evento'

  get '/aprovacoes/aprovar-usuario/:id', to: 'usuarios#aprovar_usuario', as: 'aprovar-usuario'
  get '/aprovacoes/bloquear-usuario/:id', to: 'usuarios#bloquear_usuario', as: 'bloquear-usuario'
  get '/aprovacoes', to: 'aprovacoes#aprovacoes', as: 'aprovacoes'

  get '/sobre', to: 'home#sobre', as: 'sobre'


  
  resources :turmas

  get '/turmas/nova-turma-sem-local/:id_local', to: 'turmas#new_turma_sem_local', as: 'new_turma_sem_local'

  resources :locais

  get '/encontre-a-capoeira', to: 'geolocalizacoes#index', as: 'geolocalizacoes'
  get '/encontre-a-capoeira/:tipo/:parametro', to: 'geolocalizacoes#index', as: 'geolocalizacoes-filtros'
  get '/encontre-a-capoeira/:id_local', to: 'geolocalizacoes#index_local', as: 'geolocalizacoes-local'
  get '/encontre-a-capoeira/:id_local/:id_turma', to: 'geolocalizacoes#index_local_turma', as: 'geolocalizacoes-local-turma'


  ActiveAdmin.routes(self)

app/models/turma.rb
class Turma < ApplicationRecord
  belongs_to :local
  #has_one :local
  belongs_to :usuario #default: responsavel pelo cadastro, alterado, reponsável pela turma

  validates :local_id, presence: true
  validates :hora_inicio, presence: true
  validates :hora_fim, presence: true


  def dias_da_semana

  	dias = []
  	dias.push("dom") if self.dia_dom
    dias.push("seg") if self.dia_seg
  	dias.push("ter") if self.dia_ter
  	dias.push("qua") if self.dia_qua
  	dias.push("qui") if self.dia_qui
  	dias.push("sex") if self.dia_sex
  	dias.push("sab") if self.dia_sab
  	

  	return dias.join(" / ") 

  end

  def horario_da_turma
  	
  	inicio = I18n.localize self.hora_inicio, format: :hora_minuto
  	fim = I18n.localize self.hora_fim, format: :hora_minuto

  	return inicio + " - " + fim

  end

end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]
  before_action :set_listas, only: [:new, :new_turma_sem_local, :edit, :create]

  # GET /turmas
  # GET /turmas.json
  def index
    #@turmas = Turma.includes(:local).where(usuario: current_usuario).accessible_by(current_ability, :update).order("locais.nome asc").paginate(:page => params[:page], :per_page => 10)


    @turmas =
              Local.includes(:turmas)
              .where( turmas: {usuario: current_usuario})
              .order( nome: :asc)
              .paginate(:page => params[:page], :per_page => 3)

      puts @turmas.size

  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new

    if podeCadastrarNovaTurma
      @turma = Turma.new
    else
      redirect_to turmas_path, notice: 'Você já possui uma turma cadastrada. Para cadastrar novas turmas, é necessário ser um usuário Colaborador. '
    end

  end

  def new_turma_sem_local
    @turma = Turma.new
    @turma.local = Local.find(params[:id_local])
    render :new
  end

  # GET /turmas/1/edit
  def edit


  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)
    @turma.usuario = current_usuario
    @turma.turma_ativa = true

    respond_to do |format|
      if @turma.save
        format.html { redirect_to turmas_path, notice: 'Turma salva com sucesso.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to turmas_path, notice: 'Turma atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma excluída com sucesso.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.

    def podeCadastrarNovaTurma

        if (current_usuario.usuarioLimitado? && current_usuario.turmas.exists?)
            #se usuario é limitado e ja possui local
            #true -true
            return false
        end

        return true

    end

    def set_turma
      @turma = Turma.find(params[:id])
    end

    # listas de locais , periodos, publico e etc.
    def set_listas
      #@locais = Local.all.map{|l| [l.nome,l.id]}
      @locais = Local.all
      @periodos = ['Manhã','Tarde','Noite']
      @publicos = ['Infantil','Adulto']
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turma_params

      params.require(:turma).permit(
                                      :local_id,
                                      :local_nome,
                                      :local,
                                      :hora_inicio,
                                      :hora_fim,
                                      :periodo,
                                      :publico,
                                      :observacoes,
                                      :dia_seg,
                                      :dia_ter,
                                      :dia_qua,
                                      :dia_qui,
                                      :dia_sex,
                                      :dia_sab,
                                      :dia_dom,
                                      :turma_ativa)
    end
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/turmas/_form.html.erb
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
      <% turma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


   <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
       <%= f.label :local_id, "Local onde ocorre a turma:" %>
        <p class="sublabel">Escolha o local aonde a turma acontece.
        <span>Caso não encontre o local na lista, clique para cadastrar um novo.</span> </p>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-sun-o" aria-hidden="true"></i>
        </div>
        <%= f.select :local_id, @locais.collect {|l| [ l.nome, l.id ]} , prompt: "Escolha um local" %>

      </div>
      <br>
      <div >
        <%= link_to(new_local_path) do %>
          <span class="btn btn-success btn-mini" style="text-align: center; color:white;">Cadastrar novo local</span>
        <% end %>
      </div>

       <%if params[:notice] %>
        <br>
        <p id="notice"><%= params[:notice] %></p>
       <%end%>

    </div>

  </div>

   <div class="row">

    <div class="col-md-12">
      <label> Dias que ocorre a turma:</label>
      <p class="sublabel">Escolha os dias da semana em que a turma acontece</p>
    </div>

    <div class="col-md-1 col-sm-1 col-xs-1">
      <div class="box-dia">
        <%= f.label :dia_dom, "dom" %>
        <%= f.check_box :dia_dom %>
      </div>
    </div>

    <div class="col-md-1 col-sm-1 col-xs-1">
      <div class="box-dia">
        <%= f.label :dia_seg, "seg" %>
        <%= f.check_box :dia_seg %>
      </div>
    </div>
    <div class="col-md-1 col-sm-1 col-xs-1">
      <div class="box-dia">
        <%= f.label :dia_ter, "ter" %>
        <%= f.check_box :dia_ter %>
      </div>
    </div>
    <div class="col-md-1 col-sm-1 col-xs-1">
      <div class="box-dia">
        <%= f.label :dia_qua, "qua" %>
        <%= f.check_box :dia_qua %>
      </div>
    </div>
    <div class="col-md-1 col-sm-1 col-xs-1">
      <div class="box-dia">
        <%= f.label :dia_qui, "qui" %>
        <%= f.check_box :dia_qui %>
      </div>
    </div>
    <div class="col-md-1 col-sm-1 col-xs-1">
      <div class="box-dia">
        <%= f.label :dia_sex, "sex" %>
        <%= f.check_box :dia_sex %>
      </div>
    </div>
    <div class="col-md-1 col-sm-1 col-xs-1">
      <div class="box-dia">
        <%= f.label :dia_sab, "sab" %>
        <%= f.check_box :dia_sab %>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-md-6 col-sm-12 col-xs-12">
      <%= f.label :periodo, "Período do dia:" %>
      <p class="sublabel">Escolha o período em que a turma acontece.
        <span>Essa informação ajudará os usuários a buscarem turmas em períodos específicos</span>
      </p>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-sun-o" aria-hidden="true"></i>
        </div>
        <%= f.select :periodo, options_for_select(@periodos, :periodo) , prompt: "Escolha um período" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 col-sm-12 col-xs-12">
      <%= f.label :hora_inicio, "Início:" %>
      <p class="sublabel">Hora que começa.</p>

      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-clock-o" aria-hidden="true"></i>
        </div>
         <%= f.time_field :hora_inicio, class: 'form-control' %>
      </div>

    </div>
        <div class="col-md-2 col-sm-12 col-xs-12">
      <%= f.label :hora_fim, "Fim:" %>
      <p class="sublabel">Hora que termina.</p>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-clock-o" aria-hidden="true"></i>
        </div>
        <%= f.time_field :hora_fim, class: 'form-control' %>
      </div>

    </div>
  </div>

   <div class="row">
    <div class="col-md-5 col-sm-12 col-xs-12">
      <%= f.label :publico, "Público Alvo:" %>
      <p class="sublabel">Escolha o público que frequenta a turma.</p>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-users" aria-hidden="true"></i>
        </div>
        <%= f.select :publico, options_for_select(@publicos, :publico) , prompt: "Escolha um público alvo" %>
      </div>
    </div>
  </div>


   <div class="row">
    <div class="col-md-8 col-sm-12 col-xs-12">
      <%= f.label :observacoes, "Informações adicionais:" %>
      <p class="sublabel">Descreva os pontos adcionais para complementar as informações desta turma .</p>
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-pencil" aria-hidden="true"></i>
        </div>
        <%= f.text_area :observacoes, class: "form-control", placeholder: "Observações" %>
      </div>
    </div>
  </div>


  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/js/standalone/selectize.min.js"></script>
  <script>
  $(function() {
    $('#turma_local_id').selectize({
      sortField: 'nome'
    });
  });

  </script>

app/views/turmas/edit.html.erb
<h1>Editar Turma</h1>


<%= form_for(@turma) do |f| %>

			<%= render 'form', turma: @turma, f:f %>
			
			
			<% #opcao disponivel somente ao editar %>
			<div class="row">
			    <div class="col-md-8 col-sm-12 col-xs-12">
			      <%= f.label :turma_ativa, "Exibir turma:" %>
			      <br>
			      <div class="input-group">
			        <div class="input-group-addon">
			          <i class="fa fa-check" aria-hidden="true"></i>    
			        </div>
			        <%= f.select :turma_ativa, [["Turma Ativa", true], ["Turma Desativada", false]], class: 'form-control' %>
			      </div>
			    </div>  
			</div>

			<div class="actions">
				<%= f.submit "Salvar alterações da Turma",:class => "btn btn-success btn-mini"%>
			</div>

			<% end %> 

<%= link_to 'Visualizar', @turma %> |
<%= link_to 'Voltar para tela de turmas', turmas_path %>
<br>

app/views/turmas/index.html.erb
<h1>Minhas Turmas</h1>

<%= link_to new_turma_path, class: 'btn btn-success' do %>
  <i class="fa fa-plus"></i> Cadastrar Nova Turma
<% end %>

<% if !@turmas.blank? %>
  <p id="notice"><%= notice %></p>

<% @turmas.each do |local| %>
  <table class="table table-hover table-striped" style="border: 2px solid #ddd ">

    <thead>
      <tr>
        <th colspan="2" class=" borda-bottom-1px" style="background-color: #f9f9f9; font-weight: normal; vertical-align: top; width: 50%;" >
           <p style="font-size: 14px; font-weight: bold; color:#827977;"><%=local.nome%> <span style="font-size: 12; font-weight: normal; color:#a2a2a2;">(<%=local.cidade%>)</span></p>
        </th>
        <th colspan="2" style="background-color: #f9f9f9 ;vertical-align: top;">
            <span style="font-size: 12px; font-weight: normal; margin-right: 15px;">
              <%= link_to(local) do %>
                <i class="fa fa-calendar-o"></i> Visualizar informações do local
              <% end %>
           </span>
            <span style="font-size: 12px; font-weight: normal;">
              <%= link_to(edit_local_path(local)) do %>
              <i class="fa fa-pencil"></i> Editar informações do local
            <% end %>
            </span>
        </th>
      </tr>
    </thead>

    <thead>
      <tr>
        <th  style="height:120px; width:25%; background-image: url('<%="https://maps.googleapis.com/maps/api/staticmap?center="+local.latitude.to_s+","+local.longitude.to_s+"&zoom=16&size=300x300&maptype=roadmap&markers=color:blue%7Clabel:gcb%7C"+local.latitude.to_s+","+local.longitude.to_s+"&key=AIzaSyBRm2ob56GOjnSIKFxPYrp04haa0c4Gdsc"%>');background-size: cover; background-position: center;"></th>
        <th colspan="3" style="height:120px; width:75%; background-image: url('<%=local.imagem_url.to_s%>'); background-size: cover; background-position: center;"></th>
      </tr>
    </thead>



    <thead>

      <tr>
        <th style="width: 25%">Horário</th>
        <th style="width: 25%">Dias</th>
        <th style="width: 20%">Público</th>
        <th style="width: 30%"></th>
      </tr>


    </thead>

    <tbody>
      <% local.turmas.each do |turma| %>
        <tr>
          <td>
            <%=turma.horario_da_turma%>
            <% if !turma.turma_ativa%>
              <span style="color: red;"> (desativada)</span>
            <%end%>
          </td>
          <td><%=turma.dias_da_semana%></td>
          <td><%=turma.publico%></td>
          <td>
            <%= link_to(turma) do %>
              <span style="margin-right: 5px;">
                <i class="fa fa-calendar-o"></i> Visualizar
              </span>
            <% end %>
            <%= link_to(edit_turma_path(turma)) do %>
              <span style="margin-right: 5px;">
                <i class="fa fa-pencil"></i> Editar
              </span>
            <% end %>
            <%= link_to(turma, method: :delete, data: { confirm: 'Tem certeza que deseja excluir este turma?' }) do %>
             <span style="margin-right: 5px;">
              <i class="fa fa-trash-o"></i> Excluir
              </span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<%end%>

  <%= will_paginate @turmas %>

  <br>


<% end %>

app/views/turmas/new.html.erb
		<h1>Cadastrar Nova Turma</h1>

		<%= form_for(@turma) do |f| %>

			<%= render 'form', turma: @turma, f:f %>
			
			<div class="actions">
   				<%= f.submit "Cadastrar Turma" , :class => "btn btn-success btn-mini"%>
  			
			</div>

		<% end  #end form renderizado%> 


		
		<%= link_to 'Voltar para tela de turmas', turmas_path %>
		<br><br>

app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Turma</h2>

<p>Dias: <%=@turma.dias_da_semana%></p>
<p>Horário: <%=@turma.horario_da_turma%> (<%=@turma.periodo%>)</p>
<p>Público: <%=@turma.publico%></p>

<hr>

<h4>Local da Turma</h4>
<p><%=@turma.local.nome%></p>
<p><%=@turma.local.endereco_completo%></p>
<%=image_tag(	"https://maps.googleapis.com/maps/api/staticmap
				?center=#{@turma.local.latitude},#{@turma.local.longitude}
				&zoom=16
				&size=300x300
				&maptype=roadmap
				&markers=color:blue%7Clabel:#{@turma.local.nome}%7C#{@turma.local.latitude},#{@turma.local.longitude}
				&key=AIzaSyBRm2ob56GOjnSIKFxPYrp04haa0c4Gdsc"
)%>
<br>
<br>
<%= link_to 'Editar', edit_turma_path(@turma) %> |
<%= link_to 'Voltar para a lista de turmas', turmas_path %>