config/routes.rb
#               bloquear_usuario GET    /aprovacoes/bloquear-usuario/:id(.:format)  usuarios#bloquear_usuario
#                     aprovacoes GET    /aprovacoes(.:format)                       aprovacoes#aprovacoes
#                          sobre GET    /sobre(.:format)                            home#sobre
#                     admin_root GET    /admin(.:format)                            admin/dashboard#index
# batch_action_admin_publicacoes POST   /admin/publicacoes/batch_action(.:format)   admin/publicacoes#batch_action
#              admin_publicacoes GET    /admin/publicacoes(.:format)                admin/publicacoes#index
#                                POST   /admin/publicacoes(.:format)                admin/publicacoes#create
#           new_admin_publicacao GET    /admin/publicacoes/new(.:format)            admin/publicacoes#new
#          edit_admin_publicacao GET    /admin/publicacoes/:id/edit(.:format)       admin/publicacoes#edit
#               admin_publicacao GET    /admin/publicacoes/:id(.:format)            admin/publicacoes#show
#                                PATCH  /admin/publicacoes/:id(.:format)            admin/publicacoes#update
#                                PUT    /admin/publicacoes/:id(.:format)            admin/publicacoes#update
#                                DELETE /admin/publicacoes/:id(.:format)            admin/publicacoes#destroy
#    batch_action_admin_usuarios POST   /admin/usuarios/batch_action(.:format)      admin/usuarios#batch_action
#                 admin_usuarios GET    /admin/usuarios(.:format)                   admin/usuarios#index
#                                POST   /admin/usuarios(.:format)                   admin/usuarios#create
#              new_admin_usuario GET    /admin/usuarios/new(.:format)               admin/usuarios#new
#             edit_admin_usuario GET    /admin/usuarios/:id/edit(.:format)          admin/usuarios#edit
#                  admin_usuario GET    /admin/usuarios/:id(.:format)               admin/usuarios#show
#                                PATCH  /admin/usuarios/:id(.:format)               admin/usuarios#update
#                                PUT    /admin/usuarios/:id(.:format)               admin/usuarios#update
#                                DELETE /admin/usuarios/:id(.:format)               admin/usuarios#destroy
#     batch_action_admin_eventos POST   /admin/eventos/batch_action(.:format)       admin/eventos#batch_action
#                  admin_eventos GET    /admin/eventos(.:format)                    admin/eventos#index
#                                POST   /admin/eventos(.:format)                    admin/eventos#create
#               new_admin_evento GET    /admin/eventos/new(.:format)                admin/eventos#new
#              edit_admin_evento GET    /admin/eventos/:id/edit(.:format)           admin/eventos#edit
#                   admin_evento GET    /admin/eventos/:id(.:format)                admin/eventos#show
#                                PATCH  /admin/eventos/:id(.:format)                admin/eventos#update
#                                PUT    /admin/eventos/:id(.:format)                admin/eventos#update
#                                DELETE /admin/eventos/:id(.:format)                admin/eventos#destroy
#                admin_dashboard GET    /admin/dashboard(.:format)                  admin/dashboard#index
#  batch_action_admin_categorias POST   /admin/categorias/batch_action(.:format)    admin/categorias#batch_action
#               admin_categorias GET    /admin/categorias(.:format)                 admin/categorias#index
#                                POST   /admin/categorias(.:format)                 admin/categorias#create
#            new_admin_categoria GET    /admin/categorias/new(.:format)             admin/categorias#new
#           edit_admin_categoria GET    /admin/categorias/:id/edit(.:format)        admin/categorias#edit
#                admin_categoria GET    /admin/categorias/:id(.:format)             admin/categorias#show
#                                PATCH  /admin/categorias/:id(.:format)             admin/categorias#update
#                                PUT    /admin/categorias/:id(.:format)             admin/categorias#update
#                                DELETE /admin/categorias/:id(.:format)             admin/categorias#destroy
#                 admin_comments GET    /admin/comments(.:format)                   admin/comments#index
#                                POST   /admin/comments(.:format)                   admin/comments#create
#                  admin_comment GET    /admin/comments/:id(.:format)               admin/comments#show
#                                DELETE /admin/comments/:id(.:format)               admin/comments#destroy
#                           root GET    /                                           home#index
#
# Routes for Bootsy::Engine:
# image_gallery_images GET    /image_galleries/:image_gallery_id/images(.:format)     bootsy/images#index
#                      POST   /image_galleries/:image_gallery_id/images(.:format)     bootsy/images#create
#  image_gallery_image DELETE /image_galleries/:image_gallery_id/images/:id(.:format) bootsy/images#destroy
#               images GET    /images(.:format)                                       bootsy/images#index
#                      POST   /images(.:format)                                       bootsy/images#create
#                image DELETE /images/:id(.:format)                                   bootsy/images#destroy
#

Rails.application.routes.draw do
  
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  

  #resources :publicacaos
  resources :publicacoes

  #devise_for :admin_users, ActiveAdmin::Devise.config
  
  
  devise_for :usuarios, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'cadastro', edit: 'configuracoes' }
  get 'lista_usuarios' , to: 'usuarios#lista_usuarios', as: 'lista_usuarios'



  #PERFIL
  
  get '/perfil', to: 'perfis#show', as: 'perfil_usuario'
  get '/perfil_professor/:id', to: 'perfis#public_show', as: 'perfil_publico_usuario'
  # PERFIL - FOTO PERFIL
  get '/perfil/incluir_foto' , to: 'perfis#incluir_foto' , as: 'perfil_nova_foto'
  get '/perfil/alterar_foto' , to: 'perfis#alterar_foto' , as: 'perfil_alterar_foto'
  # PERFIL - FOTO CAPA
  get '/perfil/incluir_foto_capa' , to: 'perfis#incluir_foto_capa' , as: 'perfil_nova_foto_capa'
  get '/perfil/alterar_foto_capa' , to: 'perfis#alterar_foto_capa' , as: 'perfil_alterar_foto_capa'
  # PERFIL - DESCRICAO
  get '/perfil/incluir_descricao' , to: 'perfis#incluir_descricao' , as: 'perfil_nova_descricao' 
  get '/perfil/alterar_descricao' , to: 'perfis#alterar_descricao' , as: 'perfil_alterar_descricao'
  # PERFIL - DATAS
  get '/perfil/incluir_datas' , to: 'perfis#incluir_datas' , as: 'perfil_novas_datas' 
  get '/perfil/alterar_datas' , to: 'perfis#alterar_datas' , as: 'perfil_alterar_datas'
  # PERFIL - CORDA
  get '/perfil/incluir_corda' , to: 'perfis#incluir_corda' , as: 'perfil_nova_corda' 
  get '/perfil/alterar_corda' , to: 'perfis#alterar_corda' , as: 'perfil_alterar_corda' 

  #put '/editar_perfil/:id', to: 'perfis#update', as: 'update_perfil'
  resources :perfis, only: [:update, :create]

  #END PERFIL

  #--GEOGRAFIA----------------------------

  get '/geografia/:pais', to: 'geografia#estadosprovincias', as: 'geografia_estadosprovincias'
  get '/geografia/:pais/:estado', to: 'geografia#cidades', as: 'geografia_cidades'
  
  #get '/geografia/cidades/:pais:estado', to: 'geografia#cidade', as: 'geografia_cidades'


  #END GEOGRAFIA

  #--EVENTOS----------------------------
  
  resources :eventos

  get '/eventos-professores', to: 'eventos#index_professores', as: 'index_eventos_professores'
  get '/proximos-eventos', to: 'eventos#public_proximos_eventos', as: 'proximos-eventos'
  get '/proximos-eventos/evento/:id', to: 'eventos#public_evento', as: 'publico-evento'

  #filtro de eventos
  get '/proximos-eventos/local/:p',         to: 'eventos#public_proximos_eventos_local',           as: 'publico-evento-local'
  get '/proximos-eventos/local/',           to: 'eventos#public_proximos_eventos_sem_local',       as: 'publico-evento-sem-local'
  get '/proximos-eventos/data/:a/:m',       to: 'eventos#public_proximos_eventos_data',            as: 'publico-evento-data'
  get '/proximos-eventos/usuario/:idusuario',      to: 'eventos#public_proximos_eventos_usuario',   as: 'publico-evento-usuario'


  #get '/proximos-eventos/:id', to: 'eventos#public_evento'

  #END EVENTOS


  get '/publicacoes-professores', to: 'publicacoes#index_professores', as: 'index_publicacoes_professores'
  get '/todas-publicacoes', to: 'publicacoes#public_publicacoes', as: 'todas-publicacoes'
  get '/todas-publicacoes/:nomeCategoria', to: 'publicacoes#public_publicacoes', as: 'todas-publicacoes-categoria'
  get '/todas-publicacoes/publicacao/:id', to: 'publicacoes#public_publicacao', as: 'publico-publicacao'
  #get '/proximos-eventos/:id', to: 'eventos#public_evento'

  get '/aprovacoes/aprovar-usuario/:id', to: 'usuarios#aprovar_usuario', as: 'aprovar-usuario'
  get '/aprovacoes/bloquear-usuario/:id', to: 'usuarios#bloquear_usuario', as: 'bloquear-usuario'
  get '/aprovacoes', to: 'aprovacoes#aprovacoes', as: 'aprovacoes'

  get '/sobre', to: 'home#sobre', as: 'sobre'


  
  resources :turmas

  get '/turmas/nova-turma-sem-local/:id_local', to: 'turmas#new_turma_sem_local', as: 'new_turma_sem_local'

  resources :locais

  get '/encontre-a-capoeira', to: 'geolocalizacoes#index', as: 'geolocalizacoes'
  get '/encontre-a-capoeira/:tipo/:parametro', to: 'geolocalizacoes#index', as: 'geolocalizacoes-filtros'
  get '/encontre-a-capoeira/:id_local', to: 'geolocalizacoes#index_local', as: 'geolocalizacoes-local'
  get '/encontre-a-capoeira/:id_local/:id_turma', to: 'geolocalizacoes#index_local_turma', as: 'geolocalizacoes-local-turma'


  ActiveAdmin.routes(self)

app/controllers/geolocalizacoes_controller.rb
class GeolocalizacoesController < ApplicationController

	before_action :set_locais_e_turmas_ativas, only: [:index, :index_filtro]
	before_action :set_local_e_turmas_ativas, only: [:index_local]
	before_action :set_turma_ativa, only: [:index_local_turma]
	before_action :inicializaFiltros, only: [:index, :index_local, :index_local_turma, :index_filtro]

	def index
		#@locaisDaCapoeira = Local.includes(:turmas).where.not( turmas: {id: nil}).order("turmas.hora_inicio asc")

		## DUVIDA ##
		# Esta e a maneira correta de fazer filtros?
		# Criando uma rota, filtrando os registros atraves da funcao e aproveitando a view?

		if params[:tipo] == 'p'
			#parâmetro Professor
			@locaisDaCapoeira = @locaisDaCapoeira.where( turmas: {usuario_id: params[:parametro]})
			@nomeFiltro  = Usuario.find(params[:parametro]).apelidoCompleto;


		elsif params[:tipo] == 'l'
			#parâmetro local
			@locaisDaCapoeira = @locaisDaCapoeira.where( pais: params[:parametro])

		end


	end

	def index_local

	end

	def index_local_turma

	end

	def inicializaFiltros

      set_locais_e_turmas_ativas

      professores= Array.new
      locais = Array.new

      paises_temp = CS.countries
      paises_temp.delete("BR")
      paises_temp[:BR] = "Brasil"

      for local in @locaisDaCapoeira

        localidade = [paises_temp[local.pais.to_sym], local.pais]

        for turma in local.turmas
        	professor = [ turma.usuario.apelidoCompleto, turma.usuario ]
        	professores.push(professor)
        end

       	locais.push(localidade)

       end



      @resultProfs = professores.inject(Hash.new(0)) { |hash,element|
        hash[element] +=1
        hash
      }

      resultLocais_temp = locais.inject(Hash.new(0)) { |hash,element|
        hash[element] +=1
        hash
      }

      @resultLocais = resultLocais_temp.sort


    end



    private
    # Use callbacks to share common setup or constraints between actions.

    def set_locais_e_turmas_ativas
      @locaisDaCapoeira = 	Local.includes( turmas: [:usuario] )
      						.where.not( turmas: {id: nil})
      						.where( turmas: {turma_ativa: true})
                                          .where( turmas: { usuarios: {approved: true}})
                                          .order("locais.nome asc","turmas.hora_inicio asc")
                                          .paginate(:page => params[:page], :per_page => 12)

      	#("user_extensions.company desc")
		#City.includes(:photos).where.not( photos: {city_id: nil} )
		#City.includes(:photos).where(photos: { city_id: nil })
		#City.left_outer_joins(:photos).where(photos: {id: nil})
    end

    def set_local_e_turmas_ativas
    	if params[:id_local]
     		@local = Local.includes( turmas: [:usuario] )
     					.where.not( turmas: {id: nil})
     					.where( turmas: {turma_ativa: true})
                              .where( turmas: { usuarios: {approved: true}})
     					.order("turmas.hora_inicio asc")
              .find(params[:id_local])
      	end
    end

    def set_turma_ativa
    	if (params[:id_local] && [:id_turma])
     		@turma =  	Turma.where(local_id: params[:id_local])
     					.where(turma_id: params[:id_turma])
     					.where(turma_ativa: true)

      	end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geo_params
      #params.require(:evento).permit( :titulo, :descricao, :local,
         	                          #:data_hora_inicio, :data_hora_inicio_time,:data_hora_inicio_date,
                                      #:data_hora_fim, :data_hora_fim_time, :data_hora_fim_date,
                                      #:aprovado, :usuario, :image, :image_cache, :bootsy_image_gallery_id,
                                      #:cidade, :pais, :estadoprovincia, :p, :ep, :c, :idusuario) # List here whitelisted params

    end


end

app/views/geolocalizacoes/_sidebar_encontre_a_capoeira.html.erb
<div class="side-nav-head">
	<h4>LOCAIS</h4>
</div>
<ul class="list-group list-group-bordered list-group-noicon">

	<% locais.each do |key, value| %>
		
			<li class="list-group-item">
				<%=	link_to( geolocalizacoes_filtros_path( :tipo => 'l' , :parametro => key[1] )  )do %>	
					<%= key[0]%>
					<span class="size-11 text-muted pull-right">(<%=value%>)</span>
				<% end %>
			</li>

	<% end %>
</ul>


<div class="side-nav-head">
	<h4>PROFESSORES</h4>
</div>
<ul class="list-group list-group-bordered list-group-noicon ">

	<% professores.each do |key, value| %>

			<li class="list-group-item">
				<%=	link_to( geolocalizacoes_filtros_path( :tipo => 'p' , :parametro => key[1] ) ) do %>	
					<%= key[0]%>
					<span class="size-11 text-muted pull-right">(<%=value%>)</span>
				<% end %>
			</li>

	<% end %>
</ul>
<!-- /side navigation -->

app/views/geolocalizacoes/index.html.erb
<section id="events">

	<h3>Encontre a Capoeira
		<span style="font-size: 15px;">
		<% if !@nomeFiltro.nil? %>
		 / <%=@nomeFiltro%>
		<% end %>
		</span>
	</h3>

	<div class="row">
		<div class="col-md-9 col-sm-9">

				 <div class="row">
						<!-- item -->
						<% @locaisDaCapoeira.each do |local| %>

							<div class="col-md-4 col-sm-6">
								<div class="box-flip box-color box-icon box-icon-center box-icon-round box-icon-large text-center ">
									<div class="front">
										<div class="box1 box-default tamanho500">
											<div class="box-icon-title">
												<div class="cartaz encontre" style="background-image: url('<%=local.imagem_url.to_s%>');"></div>
												<div class="nome_e_local">
													<h2 class="nome_local"><%=local.nome.truncate(50)%></h2>
													<small class="local_local"><%=local.nome_pais%> - <%=local.cidade%> </small>
												</div>
											</div>
											<br>
											<% local.turmas.take(2).each do |turma| %>

												<%= link_to geolocalizacoes_local_path(local),  :class=>"link-turma"  do %>
												<div class="turmas">
												<hr>

													<% if turma.usuario.perfil %>
														<div class="cartaz encontre avatar_turma_professor" style="background-image: url('<%=turma.usuario.perfil.imagemPerfil_url.to_s%>');"></div>
													<% else %>
														<div 	class="cartaz encontre avatar_turma_professor"
																style="background-image: url('<%= image_url("avatar2.jpg")%>');"></div>
													<% end %>
													<div class="info-turma">
														<p>
															<i class="fa fa-clock-o" aria-hidden="true"></i>
															<%=turma.horario_da_turma%></p>
														<p class="dias_da_turma">
															<i class="fa fa-calendar" aria-hidden="true"></i>
															<%=turma.dias_da_semana%>
														</p>
														<p class="nome_professor">
														<i class="fa fa-user" aria-hidden="true"></i>
															<%=turma.usuario.apelidoCompleto%>
														</p>
													</div>

												</div>
												<% end %>
											<% end %>

											<%= link_to geolocalizacoes_local_path(local),  :class=>"maisturmas"  do %>
											Ver mais
												<% if local.turmas.size > 2 %>
													<% falta = local.turmas.count - 2%>
													<% if falta == 1%>
													<%=falta%> turma
													<% else %>
													<%=falta%> turmas
													<% end %>
												<% end %>
											<% end %>
										</div>
									</div>
								</div>
								<br>
							</div>


						<% end %>

					</div>

		</div>
		<div class="col-md-3 col-sm-3">
				<!-- INLINE SEARCH -->
<!-- 				<div class="inline-search clearfix margin-bottom-30">
					<form action="" method="get" class="widget_search">
						<input type="search" placeholder="Buscar..." id="s" name="s" class="serch-input">
						<button type="submit">
							<i class="fa fa-search"></i>
						</button>
					</form>
				</div> -->
				<!-- /INLINE SEARCH -->

				<!-- <hr /> -->

				<!-- side navigation -->
				<div class="side-nav margin-bottom-60">

					<% #render 'sidebar_publicacao', categorias:@categorias %>
					<%= render 'sidebar_encontre_a_capoeira', locais:@resultLocais, professores:@resultProfs %>

					<hr>
	                <%= render 'layouts/sidebar_fb' %>


				</div>

			</div>

	</div>


    </div>
</section>


<br>
<br>

app/views/geolocalizacoes/index_local.html.erb
<section id="events">
<br>
	<h3>Encontre a Capoeira 
		<span style="font-size: 15px;">
		/ <%=@local.nome%>
		</span>
	</h3>
	
	<div class="row">
		<div class="col-md-9 col-sm-9">
		<br>
            <div class="row">
				<div class="col-md-6 col-sm-6">
					<div class="box-icon-title">
						<div class="cartaz encontre" style="background-image: url('<%=@local.imagem_url.to_s%>');">
						</div>
					</div>
					
				</div>
				<div class="col-md-6 col-sm-6">
					<div class="infolocal">
						<p>
							<i class="fa fa-home" aria-hidden="true"></i>
							<%=@local.nome%>
							</p>
						<p>
							<i class="fa fa-map-marker" aria-hidden="true"></i>
							<%=@local.endereco%></br><%=@local.cidade%> - <%=@local.estadoprovincia%> - <%=@local.nome_pais%>
						</p>
						<p>
							<i class="fa fa-phone" aria-hidden="true"></i>
							<%=@local.contato1%>
						</p>
						<p>
							<i class="fa fa-envelope" aria-hidden="true"></i>
							<%=@local.contato2%>
						</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 infolocalturmas">
				<br>
				<h4>Turmas 
					<span style="font-size: 13px;">
					/ <%=@local.nome%>
					</span>
				</h4>
				<hr>
					<% @local.turmas.each do |turma| %>
	
						
						<div class="turmas">
						<hr>

							<% if turma.usuario.perfil %>
								<div class="cartaz encontre avatar_turma_professor" style="background-image: url('<%=turma.usuario.perfil.imagemPerfil_url.to_s%>');"></div>
							<% else %>
								<div 	class="cartaz encontre avatar_turma_professor"
										style="background-image: url('<%= image_url("avatar2.jpg")%>');"></div>
							<% end %>
							<div class="info-turma">
							<br>
								<p>
									<i class="fa fa-clock-o" aria-hidden="true"></i>
									<%=turma.horario_da_turma%></p>
								<p class="dias_da_turma">
									<i class="fa fa-calendar" aria-hidden="true"></i>
									<%=turma.dias_da_semana%>
								</p>	
								<p class="nome_professor">
								<i class="fa fa-user" aria-hidden="true"></i>
									<%=turma.usuario.apelidoCompleto%>
								</p>
								<p class="email_professor">
								<i class="fa fa-envelope" aria-hidden="true"></i>
									<%=turma.usuario.email%>
								</p>
							</div>
						</div>
						<% end %>
						
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<br><br>
					<h4>Mapa
						<span style="font-size: 13px;">
							/ <%=@local.nome%>
						</span>
					</h4>
					<hr>
					<div 	class="mapalocal" 
							style="background-image: url(
'https://maps.googleapis.com/maps/api/staticmap?center=<%=@local.latitude%>,<%=@local.longitude%>&zoom=16&size=2000x300&maptype=roadmap&markers=color:blue%7Clabel:<%=@local.nome%>%7C<%=@local.latitude%>,<%=@local.longitude%>&key=AIzaSyBRm2ob56GOjnSIKFxPYrp04haa0c4Gdsc') ">
						

						
					</div>
					<br>
				</div>
			</div>
		</div>
		<div class="col-md-3 col-sm-3">
				<div class="side-nav margin-bottom-60">
					<%= render 'sidebar_encontre_a_capoeira', locais:@resultLocais, professores:@resultProfs %>
					<hr>
	                <%= render 'layouts/sidebar_fb' %>
				</div>
			</div>
		</div>
    </div>

</section>

<br>
<br>

app/views/geolocalizacoes/index_local_turma.html.erb
<p>local-turma</p>